name: Bug
about: Something broke
labels: bug
body:
  - type: textarea
    attributes: { label: What happened? }
  - type: textarea
    attributes: { label: Steps to reproduce }
  - type: textarea
    attributes: { label: Expected behavior }
