name: Feature
about: Propose a new capability
labels: enhancement
body:
  - type: textarea
    attributes: { label: Problem }
  - type: textarea
    attributes: { label: Proposal }
  - type: textarea
    attributes: { label: Acceptance Criteria }
