name: ci
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder CI
        run: echo 'CI ready – add real checks as code lands'
